CREATE TABLE STATIONS(
STN_ID INT PRIMARY KEY, 
STN_NAME VARCHAR(255), 
CITY VARCHAR(255), 
STATE VARCHAR(255));

CREATE TABLE TRAINS(
TRAIN_ID INT PRIMARY KEY, 
TRAIN_NAME VARCHAR(255), 
START_STN_ID INT, 
DEST_STN_ID INT, 
DIST_MILES FLOAT, 
FOREIGN KEY (START_STN_ID) REFERENCES STATIONS(STN_ID), 
FOREIGN KEY (DEST_STN_ID) REFERENCES STATIONS(STN_ID),
BUSINESS_CLASS_FARE FLOAT,
ECONOMY_CLASS_FARE FLOAT,
RUNNING_HRS FLOAT);

CREATE TABLE TRAIN_TIMINGS(
TRAIN_ID INT,
SL_NO INT,
STN_ID INT,
DAY_NO INT,
ARRIVES_AT TIME,
DEPARTS_AT TIME,
PRIMARY KEY (TRAIN_ID, SL_NO),
FOREIGN KEY (TRAIN_ID) REFERENCES TRAINS(TRAIN_ID), 
FOREIGN KEY (STN_ID) REFERENCES STATIONS(STN_ID));





