PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbp: <http://dbpedia.org/property/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX : <http://dbpedia.org/resource/>

SELECT ?name ?numOfStudents
WHERE {
  ?uri rdf:type dbo:University .
  ?uri rdfs:label  ?name .
  ?uri dbo:numberOfStudents ?numOfStudents .
  FILTER(lang(?name) = 'en')
  FILTER(?numOfStudents > 35000)
}
ORDER BY DESC (?numOfStudents)
LIMIT 15
