class Foo{
    public static void main(String[] args){
        System.out.print(1);
        System.out.print(" ");
        System.out.print(2);
        System.out.print(" ");
        System.out.print(3);
        System.out.print(" ");
        System.out.print(4);
        System.out.print(" ");
        System.out.print(5);
        System.out.print(" ");
        System.out.print(6);
        System.out.print(" ");
        System.out.print(7);
        System.out.print(" ");
        System.out.print(8);
        System.out.print(" ");
        System.out.print(9);
        System.out.print(" ");
        System.out.print(10);
        System.out.print(" ");
        System.out.println("");
        System.out.print(11);
        System.out.print(" ");
        System.out.print(12);
        System.out.print(" ");
        System.out.print(13);
        System.out.print(" ");
        System.out.print(14);
        System.out.print(" ");
        System.out.print(15);
        System.out.print(" ");
        System.out.print(16);
        System.out.print(" ");
        System.out.print(17);
        System.out.print(" ");
        System.out.print(18);
        System.out.print(" ");
        System.out.print(19);
        System.out.print(" ");
        System.out.print(20);
        System.out.print(" ");
        System.out.println("");
        System.out.print(21);
        System.out.print(" ");
        System.out.print(22);
        System.out.print(" ");
        System.out.print(23);
        System.out.print(" ");
        System.out.print(24);
        System.out.print(" ");
        System.out.print(25);
        System.out.print(" ");
        System.out.print(26);
        System.out.print(" ");
        System.out.print(27);
        System.out.print(" ");
        System.out.print(28);
        System.out.print(" ");
        System.out.print(29);
        System.out.print(" ");
        System.out.print(30);
        System.out.print(" ");
        System.out.println("");
        System.out.print(31);
        System.out.print(" ");
        System.out.print(32);
        System.out.print(" ");
        System.out.print(33);
        System.out.print(" ");
        System.out.print(34);
        System.out.print(" ");
        System.out.print(35);
        System.out.print(" ");
        System.out.print(36);
        System.out.print(" ");
        System.out.print(37);
        System.out.print(" ");
        System.out.print(38);
        System.out.print(" ");
        System.out.print(39);
        System.out.print(" ");
        System.out.print(40);
        System.out.print(" ");
        System.out.println("");
        System.out.print(41);
        System.out.print(" ");
        System.out.print(42);
        System.out.print(" ");
        System.out.print(43);
        System.out.print(" ");
        System.out.print(44);
        System.out.print(" ");
        System.out.print(45);
        System.out.print(" ");
        System.out.print(46);
        System.out.print(" ");
        System.out.print(47);
        System.out.print(" ");
        System.out.print(48);
        System.out.print(" ");
        System.out.print(49);
        System.out.print(" ");
        System.out.print(50);
        System.out.print(" ");
        System.out.println("");
        System.out.print(51);
        System.out.print(" ");
        System.out.print(52);
        System.out.print(" ");
        System.out.print(53);
        System.out.print(" ");
        System.out.print(54);
        System.out.print(" ");
        System.out.print(55);
        System.out.print(" ");
        System.out.print(56);
        System.out.print(" ");
        System.out.print(57);
        System.out.print(" ");
        System.out.print(58);
        System.out.print(" ");
        System.out.print(59);
        System.out.print(" ");
        System.out.print(60);
        System.out.print(" ");
        System.out.println("");
        System.out.print(61);
        System.out.print(" ");
        System.out.print(62);
        System.out.print(" ");
        System.out.print(63);
        System.out.print(" ");
        System.out.print(64);
        System.out.print(" ");
        System.out.print(65);
        System.out.print(" ");
        System.out.print(66);
        System.out.print(" ");
        System.out.print(67);
        System.out.print(" ");
        System.out.print(68);
        System.out.print(" ");
        System.out.print(69);
        System.out.print(" ");
        System.out.print(70);
        System.out.print(" ");
        System.out.println("");
        System.out.print(71);
        System.out.print(" ");
        System.out.print(72);
        System.out.print(" ");
        System.out.print(73);
        System.out.print(" ");
        System.out.print(74);
        System.out.print(" ");
        System.out.print(75);
        System.out.print(" ");
        System.out.print(76);
        System.out.print(" ");
        System.out.print(77);
        System.out.print(" ");
        System.out.print(78);
        System.out.print(" ");
        System.out.print(79);
        System.out.print(" ");
        System.out.print(80);
        System.out.print(" ");
        System.out.println("");
        System.out.print(81);
        System.out.print(" ");
        System.out.print(82);
        System.out.print(" ");
        System.out.print(83);
        System.out.print(" ");
        System.out.print(84);
        System.out.print(" ");
        System.out.print(85);
        System.out.print(" ");
        System.out.print(86);
        System.out.print(" ");
        System.out.print(87);
        System.out.print(" ");
        System.out.print(88);
        System.out.print(" ");
        System.out.print(89);
        System.out.print(" ");
        System.out.print(90);
        System.out.print(" ");
        System.out.println("");
        System.out.print(91);
        System.out.print(" ");
        System.out.print(92);
        System.out.print(" ");
        System.out.print(93);
        System.out.print(" ");
        System.out.print(94);
        System.out.print(" ");
        System.out.print(95);
        System.out.print(" ");
        System.out.print(96);
        System.out.print(" ");
        System.out.print(97);
        System.out.print(" ");
        System.out.print(98);
        System.out.print(" ");
        System.out.print(99);
        System.out.print(" ");
        System.out.print(100);
        System.out.print(" ");
        System.out.println("");
    }
}