PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbp: <http://dbpedia.org/property/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX : <http://dbpedia.org/resource/>

SELECT ?name ?foundDate ?mascot ?numOfStudents ?president ?state
WHERE {
  :Purdue_University rdfs:label ?name .
  :Purdue_University dbo:foundingDate ?foundDate .
  :Purdue_University dbo:mascot ?mascot .
  :Purdue_University dbo:numberOfStudents ?numOfStudents .
  :Purdue_University dbo:president ?president .
  :Purdue_University dbo:state ?state .
  FILTER(lang(?name) = 'en')
}
